### ISSUE TITLE
Wrong style on 'Get Started' button

### ISSUE THREAD

**Issue by SBalaguer** [paritytech/substrate-website#292]
Today navigating through the site I saw that the 'Get Started' button on https://substrate.io/developers/ seems to be wrongly styled.

![image](https://user-images.githubusercontent.com/10047147/185377861-740b221a-d29e-403b-bf84-8f7456aa63c9.png)

**Comment by jonnysmillie** [comment]
Hi @SBalaguer thanks for reporting this.

I am unable to reproduce this issue. Could you please let me know which device and browser you are using?

**Comment by jonnysmillie** [comment]
ah seeing it in firefox...

**Comment by SBalaguer** [comment]
Firefox indeed!

**Comment by jonnysmillie** [comment]
This has been fixed now @SBalaguer. Thanks again for reporting. If you notice anything else out of place please just report in the same way, it's super useful for us 👍
