### ISSUE TITLE
Adding Square One information to the Ecosystem home page 

### ISSUE THREAD

**Issue by midegdugarova** [paritytech/substrate-website#296]
Hello, 

We noticed that the https://substrate.io/ecosystem/ page is missing information on Square One program (https://substrate.io/ecosystem/square-one/). 
could we put information about it with the link under Substrate Builders Program?

**Comment by jonnysmillie** [comment]
Hi @midegdugarova thanks for submitting this request. You are correct, at the moment the Square One page is accessible only via the main navigation and not via the Ecosystem page.

1. Are you able to provide content for this new call to action?
2. Would you prefer if we create a pull request for you to review?
3. There is a feature section for the Substrate Builders Program, should the requested call to action for Square One take this form?

<img width="1321" alt="Screenshot 2022-08-29 at 10 15 07" src="https://user-images.githubusercontent.com/7614348/187155975-4c6b82ca-9e69-44dd-b5f1-79e6da1cbe9d.png">

**Comment by midegdugarova** [comment]
hi @jonnysmillie !
Thank you for your response. 

I am fine if you make a pull request for a review, the content is basically one line, I was thinking of “Start your journey. 
The Square One program provides steering recommendations to teams at every stage of the building process. ”
". 
I can't provide the picture though. 
Yes, we would like to have the same call to action as in theSubstrate Builders Program section - "Learn More", which would link to this page https://substrate.io/ecosystem/square-one/.

Thank you!

**Comment by jonnysmillie** [comment]
Hi @midegdugarova I made a PR here: https://github.com/paritytech/substrate-website/pull/299

You should be able to access a preview of the website (and the ecosystem page) with a new section that links to Square One.

We now need to make sure that the content is acceptable. I suggested some text from the existing Square One page but we do need to source an image.

Let me know if you have any further thoughts or suggestions and once we are happy we can have this reviewed and merge it. Thanks again!

**Comment by midegdugarova** [comment]
@jonnysmillie , 

I would change the "wealth of resources available to the builders" to "opportunities and initiatives available in the ecosystem", otherwise it sounds too similar to what is written under the Substrate Builders Program. 
Otherwise, looks good, thanks!

**Comment by jonnysmillie** [comment]
Just to update on this issue:

I proposed using the Square One animation or a still of the animation in this new section but we feel it does not fit well with the rest of the page so I have requested that Michel look at providing a new image.

cc. @midegdugarova @rmnprkrl

**Comment by jonnysmillie** [comment]
This has now been published on the live website.
